[font]
size = 10.0

[font.bold]
family = "Iosevka Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Iosevka Nerd Font"
style = "Bold Italic"

[colors.primary]
background = "#101b24"
foreground = "#65b3e2"

[colors.normal]
black = "#848d94"
blue = "#848d94"
cyan = "#b8c8de"
green = "#72965c"
magenta = "#3a6584"
red = "#b8c8de"
white = "#b8c8de"
yellow = "#72965c"

[font.italic]
family = "Iosevka Nerd Font"
style = "Italic"

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[window]
opacity = 0.6
padding = {x = 20,y = 20}

[window.dimensions]
columns = 80
lines = 24

#[cursor]
# Set to false to disable completely
#smooth_motion = true
# 0.0 = cursor is not moving, 1.0 = cursor moves instantly
#smooth_motion_factor = 0.6
# 0.0 = broken, 1.0 = cursor shape is unaffected by movement
#smooth_motion_spring = 0.2
# Override "block" cursor if you don't like how it looks in this fork
# I prefer "underline"
#block_replace_shape = "block"
