[font]
size = 10.0

[font.bold]
family = "Iosevka Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Iosevka Nerd Font"
style = "Bold Italic"

[colors.primary]
background = "#101b24"
foreground = "#65b3e2"

[colors.normal]
black = "#848d94"
blue = "#848d94"
cyan = "#b8c8de"
green = "#72965c"
magenta = "#3a6584"
red = "#b8c8de"
white = "#b8c8de"
yellow = "#72965c"

[font.italic]
family = "Iosevka Nerd Font"
style = "Italic"

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[window]
opacity = 0.5
padding = {x = 20,y = 20}

[window.dimensions]
columns = 80
lines = 24
