[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0\t/home/bnn)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x6\xba\0\0\0\x1e\0\0\t\xe1\0\0\x5\x81\0\0\x6\xbd\0\0\0!\0\0\t\xde\0\0\x5~\0\0\0\0\0\0\0\0\n\0\0\0\x6\xbd\0\0\0!\0\0\t\xde\0\0\x5~)

[Epanel]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x1\xc3\0\0\0\x1\0\0\x4)\0\0\x1\xf5\0\0\x1\xc4\0\0\0\x2\0\0\x4(\0\0\x1\xf4\0\0\0\0\0\0\0\0\a\x80\0\0\x1\xc4\0\0\0\x2\0\0\x4(\0\0\x1\xf4)

[FullScreen]
pos=@Point(113 1292)
screen=@Rect(0 0 2560 1440)
wide=false

[MainWindow]
QtStyle=System's default
ShowRemainingTime=true
adv-controls=4
bgSize=@Size(802 1250)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[Mediainfo]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x3\xcf\0\0\0\x1e\0\0\aa\0\0\x4\x19\0\0\x3\xd2\0\0\0!\0\0\a^\0\0\x4\x16\0\0\0\0\0\0\0\0\a\x80\0\0\x3\xd2\0\0\0!\0\0\a^\0\0\x4\x16)

[OpenDialog]
advanced=false
netMRL=
size=@Size(553 521)

[Preferences]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x3\xd2\0\0\0v\0\0\x6\xf3\0\0\x3\x33\0\0\x3\xd3\0\0\0w\0\0\x6\xf2\0\0\x3\x32\0\0\0\0\0\0\0\0\a\x80\0\0\x3\xd3\0\0\0w\0\0\x6\xf2\0\0\x3\x32)

[RecentsMRL]
list=file:///home/bnn/TEMP/Replay%202024-12-06%2022-50-43.mp4, file:///home/bnn/TEMP/Wtf/NiceOneNN.mp4, file:///mnt/data/Phone_Backup/Download/Replay_2024-09-13_17-11-15.mkv, file:///mnt/data/Phone_Backup/Download/1856628318931677618-2.mp4, file:///mnt/data/Phone_Backup/Download/3478205369370963671_61715389657.mp4, file:///mnt/data/Phone_Backup/Download/1856628318931677618.mp4, file:///home/bnn/Downloads/affirmative01.wav, file:///home/bnn/Downloads/affirmative02.wav, file:///home/bnn/Downloads/affirmative03.wav, file:///home/bnn/Downloads/ammo_pack_use.wav, file:///home/bnn/Downloads/agree05.wav, file:///home/bnn/Downloads/chainlink3.wav, file:///home/bnn/Downloads/clear01.wav, file:///home/bnn/Downloads/clearedarea03.wav, file:///home/bnn/Downloads/concrete3.wav, file:///home/bnn/Downloads/coveringfriend02.wav, file:///home/bnn/Downloads/coverme02.wav, file:///home/bnn/Downloads/death1.wav, file:///home/bnn/Downloads/death3.wav, file:///home/bnn/Downloads/damage3.wav, file:///home/bnn/Downloads/death4.wav, file:///home/bnn/Downloads/death2.wav, file:///home/bnn/Downloads/damage2.wav, file:///home/bnn/Downloads/damage1.wav, file:///home/bnn/Downloads/disagree02.wav, file:///home/bnn/Downloads/enemydown04.wav, file:///home/bnn/Downloads/enemydown03.wav, file:///home/bnn/Downloads/headshot1.wav, file:///home/bnn/Downloads/headshot2.wav, file:///home/bnn/Downloads/heardnoise03.wav
times=0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

[ToolbarProfiles]
1\ProfileName=VLC 2.x.x Style
1\Value="0|64;39;64;38;65;|0-2;64;3;1;4;64;7;9;64;10;20;19;64-4;37;65;35-4;|12;11;13;14;|43;33-4;44;|0-2;64;3;1;4;64;37;64;38;64;8;65;25;35-4;34;"
2\ProfileName=VLC 1.1.x Style
2\Value="0|64;39;64;38;65;|0-2;64;3;1;4;64;7;10;9;64-4;20;19;64-4;37;65;35-4;|12;11;13;14;|5-1;33;6-1;|0-2;64;3;1;4;64;37;64;38;64;8;65;25;35-4;34;"
3\ProfileName=VLC 0.8.x Style
3\Value="1|64;39-1;64;38;|2-1;32-4;0-5;1-5;32-5;3-5;5-5;6-5;4-5;32-5;10-1;64-1;35-1;65;|12-1;11-1;13-1;14-1;|33;37-4;|0-5;1-5;32-1;1-5;5-1;6-1;4-5;32-1;12-5;11-1;65;34-4;35-1;"
4\ProfileName=Minimalist Style
4\Value="0|64;65;|0-7;64;3-1;1-5;4-1;64;12-5;64-5;37-5;38-5;64-4;10-1;65;36-4;|11-5;13-5;14-5;|5-1;33;6-1;|0-5;64;3-5;1-5;4-5;64;12-5;65;34-4;35-1;"
5\ProfileName=One-Liner Style
5\Value="0|64;38;65;|0-4;64;3;1;4;64;7;10;9;64-4;39;64-4;37;65;36-4;|12;11;14;13;|5-1;33;6-1;|0-2;64;3;1;4;64;37;64;38;64;8;65;25;35-4;34;"
6\ProfileName=Simplest Style
6\Value="0||36-4;65-4;0-7;4-5;1-5;65-4;7-5;|12-4;11;13;||36-4;65-4;0-5;4-5;1-5;65;8-5;"
size=6
