[colors.primary]
background = "#000000"
foreground = "#ed6d24"

[colors.normal]
black = "#848d94"
blue = "#848d94"
cyan = "#888c87"
green = "#50524f"
magenta = "#3a6584"
red = "#b8c8de"
white = "#b8c8de"
yellow = "#72965c"
